name: 'looker_basket'
profile: looker_basket

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  looker_basket:
    +static_analysis: strict
    staging:
      +materialized: view
    marts:
      +materialized: table
flags:
  require_generic_test_arguments_property: true